# Generated by Django 4.2.13 on 2024-05-23 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipeuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
