# Generated by Django 4.2.13 on 2024-05-24 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_remove_recipe_rating_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='avg_rating',
            field=models.FloatField(default=0),
        ),
    ]
