# Generated by Django 4.2.13 on 2024-05-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_recipe_avg_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='comment',
        ),
        migrations.AddField(
            model_name='recipe',
            name='image_resized',
            field=models.BooleanField(default=False),
        ),
    ]
